#
# Copyright (C) Virtaal contributors.
#
# This file is part of Virtaal. It is distributed under the GPL2 or
# later license. See the LICENSE file for a copy of the license and
# the AUTHORS.md file for copyright and authorship information.

"""Digits of the CLDR 47 numbering systems that are some locale's
default, other than 0-9. Generated by
devsupport/cldr/generate_numbering_systems.py - don't edit by hand."""

DIGITS = {
    'adlm': '𞥐𞥑𞥒𞥓𞥔𞥕𞥖𞥗𞥘𞥙',
    'arab': '٠١٢٣٤٥٦٧٨٩',
    'arabext': '۰۱۲۳۴۵۶۷۸۹',
    'beng': '০১২৩৪৫৬৭৮৯',
    'cakm': '𑄶𑄷𑄸𑄹𑄺𑄻𑄼𑄽𑄾𑄿',
    'deva': '०१२३४५६७८९',
    'hmnp': '𞅀𞅁𞅂𞅃𞅄𞅅𞅆𞅇𞅈𞅉',
    'mtei': '꯰꯱꯲꯳꯴꯵꯶꯷꯸꯹',
    'mymr': '၀၁၂၃၄၅၆၇၈၉',
    'nkoo': '߀߁߂߃߄߅߆߇߈߉',
    'olck': '᱐᱑᱒᱓᱔᱕᱖᱗᱘᱙',
    'tibt': '༠༡༢༣༤༥༦༧༨༩',
}
