auto: true

name: Virtaal
description: Powerful, uncluttered XLIFF and PO editor.
latest_version: 0.7.1
author: Translate House

about_url: https://translatehouse.org/about.html
docs_url: https://docs.translatehouse.org/projects/virtaal/en/latest/
gh_url: https://github.com/translate/virtaal
contact_url: https://github.com/translate/virtaal/issues
