#!/bin/bash
cache="--cache po/.intltool-merge-cache"

intltool-merge --xml-style $cache po data/virtaal-mimetype.xml.in data/virtaal-mimetype.xml
intltool-merge --desktop-style $cache po data/virtaal.desktop.in data/virtaal.desktop
