"""Generates virtaal/support/libi18n/cldr_numbering_systems.py: the
digits of each CLDR numbering system that is some Babel locale's
default, other than 0-9. Babel formats numbers with 0-9 whatever the
numbering system.

Needs Babel and network access (for CLDR's numberingSystems.json, at
the CLDR version Babel ships). Rerun after upgrading Babel.
"""
import json
import os
import urllib.request

from babel import Locale, core, localedata

NUMBERING_SYSTEMS_URL = ("https://raw.githubusercontent.com/unicode-org/cldr-json/"
                         "%s.0.0/cldr-json/cldr-core/supplemental/numberingSystems.json")
LATIN = "0123456789"
OUTPUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                      "virtaal", "support", "libi18n", "cldr_numbering_systems.py")

HEADER = '''#
# Copyright (C) Virtaal contributors.
#
# This file is part of Virtaal. It is distributed under the GPL2 or
# later license. See the LICENSE file for a copy of the license and
# the AUTHORS.md file for copyright and authorship information.

"""Digits of the CLDR %s numbering systems that are some locale's
default, other than 0-9. Generated by
devsupport/cldr/generate_numbering_systems.py - don't edit by hand."""

DIGITS = {
'''


def main():
    version = core.get_global("cldr")["version"]
    with urllib.request.urlopen(NUMBERING_SYSTEMS_URL % version) as response:
        systems = json.load(response)["supplemental"]["numberingSystems"]

    used = {Locale.parse(code).default_numbering_system for code in localedata.locale_identifiers()}
    table = {name: systems[name]["_digits"] for name in used
             if systems[name].get("_digits", LATIN) != LATIN}

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(HEADER % version)
        for name in sorted(table):
            f.write("    %r: %r,\n" % (name, table[name]))
        f.write("}\n")
    print("Wrote %d numbering systems to %s" % (len(table), OUTPUT))


if __name__ == "__main__":
    main()
