"""Generates virtaal/support/libi18n/cldr_digits.py: the digits of each
locale's default CLDR numbering system, where they aren't 0-9 or differ
from those of the locale's language.

Needs Babel (for each locale's default numbering system) and network
access (for CLDR's numberingSystems.json, at the CLDR version Babel
ships). Rerun after upgrading Babel.
"""
import json
import os
import urllib.request

from babel import Locale, core, localedata

NUMBERING_SYSTEMS_URL = ("https://raw.githubusercontent.com/unicode-org/cldr-json/"
                         "%s.0.0/cldr-json/cldr-core/supplemental/numberingSystems.json")
LATIN = "0123456789"
OUTPUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                      "virtaal", "support", "libi18n", "cldr_digits.py")

HEADER = '''#
# Copyright (C) Virtaal contributors.
#
# This file is part of Virtaal. It is distributed under the GPL2 or
# later license. See the LICENSE file for a copy of the license and
# the AUTHORS.md file for copyright and authorship information.

"""Default digits per locale from CLDR %s, where they aren't 0-9 or
differ from those of the locale's language. Generated by
devsupport/cldr/generate_digits.py - don't edit by hand."""

DIGITS = {
'''


def main():
    version = core.get_global("cldr")["version"]
    with urllib.request.urlopen(NUMBERING_SYSTEMS_URL % version) as response:
        systems = json.load(response)["supplemental"]["numberingSystems"]

    def digits(code):
        return systems[Locale.parse(code).default_numbering_system]["_digits"]

    table = {}
    for code in localedata.locale_identifiers():
        language = code.split("_")[0]
        if digits(code) != (digits(language) if code != language else LATIN):
            table[code] = digits(code)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(HEADER % version)
        for code in sorted(table):
            f.write("    %r: %r,\n" % (code, table[code]))
        f.write("}\n")
    print("Wrote %d locales to %s" % (len(table), OUTPUT))


if __name__ == "__main__":
    main()
