#!/bin/bash
# Builds dist/Virtaal.app: a real macOS .app bundle wrapping this checkout,
# not a standalone/distributable build. It execs into whatever Python
# already runs `bin/virtaal` here (a local .venv, or a system python3) -
# nothing is vendored.
#
# What this fixes: Finder now has a real Info.plist to read - a proper
# icon, and file-type/"Open With" association for the formats
# translate-toolkit knows about (previously none of that existed at all,
# running via a bare `python3 bin/virtaal`) - and something that can
# plausibly be code-signed eventually.
#
# What this does NOT fix: the native menu bar/Dock still show "Python",
# not "Virtaal", while actually running. Homebrew's Python is a
# framework build with a mechanism baked into the interpreter itself
# that transparently re-launches through its own companion
# Resources/Python.app whenever it needs to open windows - a shell
# launcher, physically copying the interpreter into this bundle, and
# the documented __PYVENV_LAUNCHER__ override all still resolve to
# Homebrew's own Python.app, not this one. A real fix needs either
# vendoring the whole Python.framework (untested, and GTK3/PyGObject's
# own dylibs are separately Homebrew-linked with absolute paths so it
# likely wouldn't be fully self-contained even then) or switching away
# from a framework-build Python for this purpose. Not attempted here.
set -eu
cd "$(git rev-parse --show-toplevel)"

APP="dist/Virtaal.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

PYTHON="$PWD/.venv/bin/python3"
[ -x "$PYTHON" ] || PYTHON="python3"

"$PYTHON" devsupport/packaging/macos/generate_info_plist.py "$APP/Contents/Info.plist"
cp devsupport/virtaal.icns "$APP/Contents/Resources/virtaal.icns"
cp devsupport/mac-bundle/VirtaalDocument.icns "$APP/Contents/Resources/VirtaalDocument.icns"

cat > "$APP/Contents/MacOS/Virtaal" <<'LAUNCHER'
#!/bin/bash
# Generated by devsupport/packaging/macos/build.sh - not meant to be hand-edited.
#
# Finds the repo this bundle was built from (4 levels up from here:
# Contents/MacOS/Virtaal -> Contents -> Virtaal.app -> dist -> repo root)
# and execs into it. Override with VIRTAAL_REPO_ROOT if the bundle gets
# moved somewhere else on its own.
#
# Known limitation: the menu bar/Dock will still show "Python", not
# "Virtaal", while running - see the header comment in build.sh for why.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
repo_root="${VIRTAAL_REPO_ROOT:-$(cd "$here/../../../.." && pwd)}"

python="$repo_root/.venv/bin/python3"
[ -x "$python" ] || python="python3"

export PYTHONPATH="$repo_root"
# A Finder/LaunchServices-launched process doesn't inherit a shell's cwd -
# cd to the repo root first so relative arguments resolve the same way
# they would running `bin/virtaal somefile.po` directly from a terminal
# there.
cd "$repo_root"
exec "$python" "$repo_root/bin/virtaal" "$@"
LAUNCHER
chmod +x "$APP/Contents/MacOS/Virtaal"

echo "Built $APP"
