#!/bin/bash

XGETTEXT_ARGS='--copyright-holder="Zuza Software Foundation (Translate.org.za)"  --package-name "VirTaal" --package-version `egrep "^ver " ../virtaal/__version__.py | sed "s/ver = //;s/\"//g"`'
export XGETTEXT_ARGS

intltool-update $*
