#!/bin/bash

./intltool-update --pot
podebug --rewrite=xxx -f "" --progress=none virtaal.pot de_DE.po
podebug --rewrite=xxx -f "" --progress=none gtk20-lite.pot de_DE-lite.po
for po in $(ls *.po | egrep -v lite)
do
	modir=mo/$(basename $po .po)/LC_MESSAGES
        gtklite=$(basename $po .po)-lite.po
	mkdir -p $modir
	msgfmt -o $modir/virtaal.mo $po
        if [ -f $gtklite ]; then
		msgfmt -o $modir/gtk20.mo $gtklite
	fi
done

lang=$1
export LANGUAGE=../../../../../../../../$(pwd)/mo/${lang:-de_DE}:$LANGUAGE
echo $LANGUAGE
# This assumes that the following executable is in your PATH
virtaal
