#!/usr/bin/env python3
#
# Copyright (C) Virtaal contributors.
#
# This file is part of Virtaal. It is distributed under the GPL2 or
# later license. See the LICENSE file for a copy of the license and
# the AUTHORS.md file for copyright and authorship information.

"""Check that every pyproject.toml [project.dependencies] entry has a
matching module in virtaal-python-deps.yaml.

flatpak-builder's sandboxed build has no network access during the
module-build step, so each pip package's source must be pre-declared
there with a pinned URL+sha256. That file is hand-maintained, not
regenerated by CI, so it silently drifts whenever pyproject.toml's
dependency list changes.

Parses both files with plain string/regex extraction rather than
tomllib or PyYAML: pyproject.toml declares support back to Python 3.10
(tomllib is 3.11+), and adding a parsing dependency just for this check
would be its own kind of self-defeating drift risk."""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
PYPROJECT = REPO_ROOT / 'pyproject.toml'
DEPS_YAML = REPO_ROOT / 'devsupport' / 'packaging' / 'flatpak' / 'virtaal-python-deps.yaml'


def normalize(name):
    """A package/module name, lowercased with '.'/'_'/'-' collapsed to
    '-' so e.g. "fluent.syntax" and "fluent-syntax" compare equal."""
    return re.sub(r'[._-]+', '-', name.strip()).lower()


def pyproject_dependency_names(text):
    match = re.search(r'dependencies\s*=\s*\[(.*?)\]', text, re.DOTALL)
    if not match:
        raise ValueError('no [project.dependencies] list found in pyproject.toml')
    # Drop full-line comments first - several here contain their own
    # quotes/apostrophes (e.g. "Virtaal's"), which would otherwise be
    # picked up as bogus requirement strings by the regex below.
    block = '\n'.join(
        line for line in match.group(1).splitlines() if not line.strip().startswith('#')
    )
    names = []
    for requirement in re.findall(r'["\']([^"\']+)["\']', block):
        # PEP 508: name is the leading identifier, before any version
        # specifier/extra/marker.
        name_match = re.match(r'^([A-Za-z0-9][A-Za-z0-9._-]*)', requirement)
        if name_match:
            names.append(name_match.group(1))
    return names


def flatpak_module_names(text):
    # Module entries are "  - name: <module>" at 2-space indent, directly
    # under modules:; nested source/build-command list items sit deeper
    # and never use a "name:" key, so this indentation-scoped pattern
    # can't pick them up by accident.
    return re.findall(r'^  - name:\s*(\S+)\s*$', text, re.MULTILINE)


def main():
    pyproject_deps = pyproject_dependency_names(PYPROJECT.read_text(encoding='utf-8'))
    module_names = flatpak_module_names(DEPS_YAML.read_text(encoding='utf-8'))
    known = set()
    for module in module_names:
        if module.lower().startswith('python3-'):
            known.add(normalize(module[len('python3-'):]))

    missing = [dep for dep in pyproject_deps if normalize(dep) not in known]

    if missing:
        print('pyproject.toml [project.dependencies] has package(s) with no matching')
        print('module in %s:' % DEPS_YAML.relative_to(REPO_ROOT))
        for dep in missing:
            print(' - %s (expected a module named python3-%s)' % (dep, dep))
        print()
        print('Add a pinned module entry for each (see the file header for how it was')
        print('originally generated via flatpak-pip-generator).')
        return 1

    print('All %d pyproject.toml dependencies have a matching flatpak module.' % len(pyproject_deps))
    return 0


if __name__ == '__main__':
    sys.exit(main())
