#!/usr/bin/env python3
#
# Copyright (C) Virtaal contributors.
#
# This file is part of Virtaal. It is distributed under the GPL2 or
# later license. See the LICENSE file for a copy of the license and
# the AUTHORS.md file for copyright and authorship information.

"""Writes po/virtaal.priorities.yaml: each message's translation
priority level, from what harvest_sources.py saw on screen and the rules
in po/priorities.toml (which also explains the levels).

    generate_priorities.py HARVEST.json [HARVEST.json ...]

writes the whole file, from every platform's harvest. With --level1-only
only level 1 is updated from the harvest, and the rest of the committed
file is kept. With --check the committed file is left alone: it reports
how it differs from the harvest, --refresh writes the level-1 update to
a file to commit, and --full the whole file, for a string freeze.

Needs the pseudo-source catalogs the harvest ran with (--localedir).
"""

import argparse
import importlib.util
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
RULES = os.path.join(REPO_ROOT, "po", "priorities.toml")
TEMPLATE = os.path.join(REPO_ROOT, "po", "virtaal.pot")
OUTPUT = os.path.join(REPO_ROOT, "po", "virtaal.priorities.yaml")
LINGUAS = os.path.join(REPO_ROOT, "po", "LINGUAS")

FORMAT = 1
LEVELS = ("1", "1~", "2", "3")
LEVEL_ONE = ("1", "1~")
LANGUAGES, COUNTRIES = "iso639-3", "iso3166-1"
PRIORITIES = [
    {"id": "1", "name": "Level 1 core"},
    {"id": "1~", "name": "Level 1"},
    {"id": "2", "name": "Level 2"},
    {"id": "3", "name": "Level 3"},
]
TAG_RE = re.compile(r"\b(?:vt|gtk|glib|iso|spell|mac)!?:")
HEADER = """\
# Generated by devsupport/pseudo-translation/generate_priorities.py from
# po/priorities.toml's rules and what Virtaal shows - don't edit it. See
# po/README.md.
"""


def _resolver():
    spec = importlib.util.spec_from_file_location("resolve_sources", os.path.join(HERE, "resolve_sources.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_rules(path=RULES):
    import tomllib
    with open(path, "rb") as f:
        return tomllib.load(f)


def _key(original):
    """A message's key, as Virtaal identifies a unit: msgctxt and msgid,
    without the plural."""
    return original.split("\0")[0]


def sighting_level(rules, screen, window, within):
    for rule in rules.get("seen", []):
        if all(re.search(rule[field], TAG_RE.sub("", value or ""))
               for field, value in (("screen", screen), ("window", window), ("within", within))
               if field in rule):
            return rule["priority"]
    return "3"


def seen_levels(harvests, catalogs, rules):
    """{domain: {key: level}} for every message seen on screen."""
    levels = {}
    resolve_text = _resolver().resolve_text
    for harvest in harvests:
        for record in harvest["strings"]:
            if not record.get("shown", True):
                continue
            level = sighting_level(rules, record["screen"], record.get("window"), record.get("within"))
            if record.get("tooltip") and "tooltips" in rules:
                level = max(level, rules["tooltips"]["priority"], key=LEVELS.index)
            for domain, original in resolve_text(record["text"], catalogs):
                if original is None:
                    continue
                domain_levels = levels.setdefault(domain, {})
                key = _key(original)
                if key not in domain_levels or LEVELS.index(level) < LEVELS.index(domain_levels[key]):
                    domain_levels[key] = level
    return levels


def template_messages(path=TEMPLATE):
    """{key: [source file, ...]} for each message in virtaal.pot."""
    from translate.storage import po
    store = po.pofile.parsefile(path)
    return {unit.getid(): [location.rpartition(":")[0] if location.rpartition(":")[2].isdigit() else location
                           for location in unit.getlocations()]
            for unit in store.units if not unit.isheader() and not unit.isobsolete()}


def read_linguas(path=LINGUAS):
    with open(path, encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip() and not line.startswith("#")]


def _catalog_msgids(domain):
    import pycountry
    generator = _resolver()._generator()
    path = generator.fullest_catalog([pycountry.LOCALES_DIR], domain)
    return set(generator.read_mo_originals(path)) if path else set()


def name_msgids(code, languages, countries):
    """([language msgid ...], country msgid or None) Virtaal looks up to
    name code - translate_compat.tr_lang(): the catalog's own name for the
    code first, then translate-toolkit's name - keeping those pycountry's
    catalogs have."""
    import pycountry
    from translate.lang import data

    from virtaal.support import translate_compat
    base = code.split("@")[0].split("_")[0]
    language = pycountry.languages.get(alpha_2=base) if len(base) == 2 else pycountry.languages.get(alpha_3=base)
    candidates = [language.name] if language else []
    name = data.languages.get(code, (None,))[0]
    country = None
    if name is not None:
        match = translate_compat.dialect_name_re.match(name)
        if match and match.group(2) != "macrolanguage":
            name, country = match.groups()
        candidates += [name, translate_compat._fix_language_name(name)]
    return ([m for m in dict.fromkeys(candidates) if m in languages],
            country if country in countries else None)


def apply_names(levels, rules, linguas=()):
    """Language and country names from the rules alone, not the harvest:
    English, the languages Virtaal ships (linguas) and the countries of
    their variants, and the languages of wider communication. A name
    Virtaal has no catalog entry for is left out (and reported)."""
    names = rules.get("names", {})
    levels = {domain: dict(keys) for domain, keys in levels.items() if domain not in (LANGUAGES, COUNTRIES)}
    language_ids, country_ids = _catalog_msgids(LANGUAGES), _catalog_msgids(COUNTRIES)
    languages, countries, unnamed = {}, {}, set()

    def add(table, name, priority):
        table[name] = min(table.get(name, priority), priority, key=LEVELS.index)

    def add_code(code, priority):
        found, country = name_msgids(code, language_ids, country_ids)
        for msgid in found:
            add(languages, msgid, priority)
        if country:
            add(countries, country, priority)
        if not found:
            unnamed.add(code)

    if "supported" in names:
        for code in linguas:
            add_code(code, names["supported"])
    wider = names.get("wider", {})
    for code in wider.get("languages", []):
        add_code(code, wider["priority"])
    if "english" in names:
        languages["English"] = names["english"]
    for code in sorted(unnamed):
        print("No %s catalog entry names %s, so it's always shown in English" % (LANGUAGES, code), file=sys.stderr)
    if languages:
        levels[LANGUAGES] = languages
    if countries:
        levels[COUNTRIES] = countries
    return levels


def is_x(rules, key):
    msgid = key.rpartition("\x04")[2]
    x = rules.get("x", {})
    return msgid in x.get("msgids", []) or any(re.search(p, msgid) for p in x.get("patterns", []))


def assign(seen, messages, rules, linguas=()):
    """{domain: {key: level}}: what was seen, every virtaal.pot message
    (its file's level if never seen), the rules' overrides,
    and x where the rules say."""
    levels = {domain: dict(keys) for domain, keys in seen.items()}
    virtaal = levels.setdefault("virtaal", {})
    virtaal = {key: level for key, level in virtaal.items() if key in messages}
    for key, files in messages.items():
        if key in virtaal:
            continue
        virtaal[key] = next((rule["priority"] for rule in rules.get("unseen", [])
                             if any(re.search(rule["file"], name) for name in files)), "3")
    levels["virtaal"] = virtaal
    levels = apply_names(levels, rules, linguas)
    overrides = {msgid: rule["priority"] for rule in rules.get("override", []) for msgid in rule["msgids"]}
    return {domain: {key: "x" if is_x(rules, key) else overrides.get(key.rpartition("\x04")[2], level)
                     for key, level in keys.items()}
            for domain, keys in levels.items()}


def stale_rules(rules, messages):
    """The msgids po/priorities.toml names that virtaal.pot no longer has."""
    msgids = {key.rpartition("\x04")[2] for key in messages}
    named = rules.get("x", {}).get("msgids", []) + [m for rule in rules.get("override", []) for m in rule["msgids"]]
    return sorted(m for m in named if m not in msgids)


def to_file(levels, pot_date):
    return {
        "format": FORMAT,
        "pot-creation-date": pot_date,
        "priorities": PRIORITIES,
        "domains": {domain: {level: sorted(key for key, value in keys.items() if value == level)
                             for level in LEVELS + ("x",)
                             if any(value == level for value in keys.values())}
                    for domain, keys in sorted(levels.items())},
    }


def write_file(path, data):
    import yaml
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, width=4096)


def read_file(path):
    import yaml
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def from_file(data):
    return {domain: {key: level for level, keys in by_level.items() for key in keys}
            for domain, by_level in data["domains"].items()}


def level1_refresh(committed, candidate):
    """committed with only level 1 brought up to date: a message candidate
    puts in level 1, or committed had there, takes candidate's level
    (or is dropped, if candidate no longer has it)."""
    result = {domain: dict(keys) for domain, keys in committed.items()}
    for domain in set(committed) | set(candidate):
        old, new = committed.get(domain, {}), candidate.get(domain, {})
        keys = result.setdefault(domain, {})
        for key in set(old) | set(new):
            if old.get(key) in LEVEL_ONE or new.get(key) in LEVEL_ONE:
                if key in new:
                    keys[key] = new[key]
                else:
                    keys.pop(key, None)
    return {domain: keys for domain, keys in result.items() if keys}


def drift(committed, candidate):
    """([(domain, key, old, new) ...] for level 1, [...] for the rest),
    "?" for a message one side lacks."""
    level_one, other = [], []
    for domain in sorted(set(committed) | set(candidate)):
        old, new = committed.get(domain, {}), candidate.get(domain, {})
        for key in sorted(set(old) | set(new)):
            before, after = old.get(key, "?"), new.get(key, "?")
            if before == after:
                continue
            change = (domain, key, before, after)
            (level_one if before in LEVEL_ONE or after in LEVEL_ONE else other).append(change)
    return level_one, other


def _code(text):
    """text as a Markdown code span, so markup in a message shows as
    typed."""
    fence = "`" * (max((len(run) for run in re.findall("`+", text)), default=0) + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return fence + pad + text + pad + fence


def _describe(changes, limit=20):
    lines = ["- %s: %s (%s -> %s)" % (domain, _code(key.replace("\x04", " | ").replace("\n", "\\n")), before, after)
             for domain, key, before, after in changes[:limit]]
    if len(changes) > limit:
        lines.append("- ... and %d more" % (len(changes) - limit))
    return lines


def _messages(count):
    return "%d message%s" % (count, "" if count == 1 else "s")


def report(level_one, other):
    """The --check report as Markdown, and the GitHub annotations."""
    lines = ["## Translation priorities", ""]
    annotations = []
    if not level_one and not other:
        lines.append("po/virtaal.priorities.yaml matches what Virtaal shows.")
    if level_one:
        lines += ["Level 1 is out of date (%s):" % _messages(len(level_one)), ""] + _describe(level_one) + [""]
        annotations.append("::warning::Level-1 priorities are out of date - commit the level-1 refresh artifact")
    if other:
        lines += ["Levels 2 and 3 differ (%s); updated at the next string freeze:" % _messages(len(other)), ""]
        lines += _describe(other)
        annotations.append("::notice::%s at a different level 2 or 3 than po/virtaal.priorities.yaml "
                           "says; updated at the next string freeze" % _messages(len(other)))
    return "\n".join(lines) + "\n", annotations


def _pot_date():
    from translate.storage import po
    return po.pofile.parsefile(TEMPLATE).parseheader().get("POT-Creation-Date", "")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("harvests", nargs="+", metavar="HARVEST", help="harvest_sources.py's JSON output")
    parser.add_argument("--localedir", default=os.path.join(sys.prefix, "share", "locale"),
                        help="Where the pseudo-source catalogs are (default: sys.prefix/share/locale)")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--level1-only", action="store_true", help="update only level 1 of the committed file")
    group.add_argument("--check", action="store_true", help="report how the committed file differs; write nothing")
    parser.add_argument("--refresh", metavar="PATH", help="with --check, write the level-1 update here")
    parser.add_argument("--full", metavar="PATH", help="with --check, write the whole file here (for a string freeze)")
    args = parser.parse_args()

    harvests = []
    for path in args.harvests:
        with open(path, encoding="utf-8") as f:
            harvests.append(json.load(f))
    rules = load_rules()
    seen = seen_levels(harvests, _resolver().load_catalogs(args.localedir), rules)
    messages = template_messages()
    for msgid in stale_rules(rules, messages):
        print("::warning::po/priorities.toml names %r, which po/virtaal.pot no longer has" % msgid)
    candidate = assign(seen, messages, rules, read_linguas())

    if not (args.level1_only or args.check):
        write_file(OUTPUT, to_file(candidate, _pot_date()))
        return

    committed_file = read_file(OUTPUT)
    committed = from_file(committed_file)
    refreshed = to_file(level1_refresh(committed, candidate), committed_file["pot-creation-date"])

    if args.level1_only:
        write_file(OUTPUT, refreshed)
        return

    level_one, other = drift(committed, candidate)
    text, annotations = report(level_one, other)
    print(text)
    for annotation in annotations:
        print(annotation)
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as f:
            f.write(text)
    if args.refresh and level_one:
        write_file(args.refresh, refreshed)
    if args.full and (level_one or other):
        write_file(args.full, to_file(candidate, _pot_date()))


if __name__ == "__main__":
    main()
