name: Validate Jekyll build

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
